### PR TITLE
Incorrect sequence number incoding in the C client

### LINKED ISSUE #15: Incorrect sequence number incoding in the C client
The sequence number used in ORP should be coded in Big-Endian (See https://docs.octave.dev/docs/octave-resource-protocol#sequence)

In ORP C client, when an ORP header is encoded, the sequence is encoded in little-endian and the incoming sequence number is decoded in little-endian

### PR DESCRIPTION
**Pull request by fdur**
Fix some issues in sequence number in the C client:
- Increment the sequence number when the C client sends an ORP request to the edge
- Sequence number decoding from big-endian

### CODE REVIEW

File: clients/c/src/orpProtocol.c [hunk 1]
```diff
@@ -937,8 +938,10 @@ static bool orp_ProtocolDecode_v1
             offset = ORP_OFFSET_DATA_TYPE;
             break;
         }
-        msg->sequenceNum = (pktBuf[ORP_OFFSET_SEQ_NUM] << 8) & 0xFF00;
-        msg->sequenceNum += pktBuf[ORP_OFFSET_SEQ_NUM + 1] & 0x00FF;
+
```
Comment (gbetous-swir) [inline clients/c/src/orpProtocol.c:941]: Please add a comment to clearly define the used endianness

File: clients/c/src/orpProtocol.c [hunk 2]
```diff
@@ -1109,8 +1112,17 @@ static bool orp_ProtocolEncode_v1
...
             break;
         }
-        packet[ORP_OFFSET_SEQ_NUM]     = (msg->sequenceNum & 0x00FF);
-        packet[ORP_OFFSET_SEQ_NUM + 1] = (msg->sequenceNum & 0xFF00) >> 8;
+
+        // Copy Sequence Number from Request or increment it in case of request sent by the device
+        if ((packet[ORP_OFFSET_PACKET_TYPE] != ORP_PKT_SYNC_SYN) && isupper(packet[ORP_OFFSET_PACKET_TYPE]))
+        {
+            // The device will send a request -> increment the Sequence Number
+            last_received_seq_number += 1;
```
Comment (gbetous-swir) [inline clients/c/src/orpProtocol.c:1120]: So this variable does not contain the "last_received_seq_number" anymore, but the "seq_number" of the next packet. I guess that it would be easier to understand using a new variable.

**Review by Nico26-sw — APPROVED** [review]

**Review by gbetous-swir — APPROVED** [review]
Some minor comments

**Comment by gbetous-swir** [comment]
Perfect, thanks !

**Review by gbetous-swir — APPROVED** [review]
